name: us-cities-health
channels:
  - defaults
  - conda-forge
dependencies:
  - Sphinx
  - black
  - pandas
  - numpy
  - matplotlib
  - statsmodels
  - seaborn
  - scikit-learn
  - jupyter
  - flake8
  - python-dotenv>=0.5.1
